# Generated by Django 4.1 on 2023-03-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_text_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=50, null=True)),
                ('postfixess', models.CharField(max_length=100, null=True)),
                ('suffixes', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.AddField(
            model_name='text',
            name='lemmas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.word'),
        ),
    ]
