# Generated by Django 4.1 on 2023-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_word_text_lemmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
