# Generated by Django 4.1 on 2023-03-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_postfixess_word_postfixes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='postfixes',
            new_name='prefixes',
        ),
    ]
