# Generated by Django 4.1 on 2023-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_postfixes_word_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='body',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
