# Generated by Django 4.1 on 2023-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_word_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='body',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
