# Generated by Django 4.1 on 2023-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_word_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='trees',
            field=models.TextField(null=True, verbose_name='Tree'),
        ),
    ]
