# Generated by Django 4.1 on 2023-04-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_text_trees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='trees',
            new_name='tree',
        ),
    ]
