# Generated by Django 4.1 on 2023-04-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_trees_text_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='semanticTree',
            field=models.TextField(null=True, verbose_name='Semantic Tree'),
        ),
    ]
